# Generated by Django 6.0.5 on 2026-06-20 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidat', '0002_initial'),
        ('entreprise', '0001_initial'),
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationdirecte',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='candidat.candidat'),
        ),
        migrations.AddField(
            model_name='demandeverification',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='raisonSocialeRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises_liees', to='referentiel.raisonsociale', verbose_name='Raison sociale'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='secteurActiviteRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises', to='referentiel.secteuractivite', verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='statutCompteRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises', to='referentiel.statutcompte', verbose_name='Statut du compte (référentiel)'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='typeRaisonSocialeRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises_directes', to='referentiel.typeraisonsociale', verbose_name='Forme juridique'),
        ),
        migrations.AddField(
            model_name='demandeverification',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_verification', to='entreprise.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='invitationentretien',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_entretien', to='candidat.candidat'),
        ),
        migrations.AddField(
            model_name='invitationpostuler',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recues', to='candidat.candidat'),
        ),
        migrations.AddField(
            model_name='message',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='candidat.candidat', verbose_name='Candidat destinataire'),
        ),
        migrations.AddField(
            model_name='message',
            name='candidature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='candidat.candidature', verbose_name='Candidature liée'),
        ),
        migrations.AddField(
            model_name='messagedirect',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='entreprise.conversationdirecte'),
        ),
        migrations.AddField(
            model_name='modelemessage',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_messages', to='entreprise.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='modelemessage',
            name='statut',
            field=models.ForeignKey(blank=True, help_text='Pour les modèles déclenchés par un changement de statut de candidature.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modeles_messages', to='referentiel.statut', verbose_name='Statut associé'),
        ),
        migrations.AddField(
            model_name='modelemessage',
            name='typeEntretien',
            field=models.ForeignKey(blank=True, help_text="Pour les modèles utilisés lors de la planification d'un entretien (RH, Technique…).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_messages', to='referentiel.typeentretien', verbose_name="Type d'entretien associé"),
        ),
        migrations.AddField(
            model_name='message',
            name='modele_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='entreprise.modelemessage', verbose_name='Modèle utilisé'),
        ),
        migrations.AddField(
            model_name='notificationrecruteur',
            name='candidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recruteurs', to='candidat.candidat', verbose_name='Candidat concerné'),
        ),
        migrations.AddField(
            model_name='notificationrecruteur',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_admin', to='entreprise.entreprise', verbose_name='Entreprise (compte admin)'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='anneesExperience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='referentiel.anneesexperience', verbose_name="Années d'expérience"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='referentiel.contrat', verbose_name='Contrat (référentiel)'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='deviseRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='referentiel.devise', verbose_name='Devise (référentiel)'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='diplome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='referentiel.diplome', verbose_name='Diplôme requis'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='entreprise.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='langues',
            field=models.ManyToManyField(blank=True, related_name='offres', to='referentiel.langue', verbose_name='Langues'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='modeTravailRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='referentiel.modetravail', verbose_name='Mode de travail (référentiel)'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='niveauEtudeRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='referentiel.niveauetude', verbose_name="Niveau d'études (référentiel)"),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='paysRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='referentiel.pays', verbose_name='Pays (référentiel)'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='posteRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='referentiel.poste', verbose_name='Poste (référentiel)'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='typesCompetence',
            field=models.ManyToManyField(blank=True, related_name='offres', to='referentiel.typecompetence', verbose_name='Types de compétence'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='villesRef',
            field=models.ManyToManyField(blank=True, related_name='offres', to='referentiel.ville', verbose_name='Villes (référentiel)'),
        ),
        migrations.AddField(
            model_name='notificationrecruteur',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recruteurs', to='entreprise.offreemploi', verbose_name='Offre concernée'),
        ),
        migrations.AddField(
            model_name='invitationpostuler',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='entreprise.offreemploi'),
        ),
        migrations.AddField(
            model_name='invitationentretien',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_entretien', to='entreprise.offreemploi'),
        ),
        migrations.AddField(
            model_name='offreemploirecruteur',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruteurs_createurs', to='entreprise.offreemploi', verbose_name='Offre'),
        ),
        migrations.AddField(
            model_name='parametreentreprise',
            name='entreprise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='entreprise.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='partageprofilexterne',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages_externes', to='candidat.candidat', verbose_name='Candidat partagé'),
        ),
        migrations.AddField(
            model_name='partageprofilexterne',
            name='entreprise_partageur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partages_profils_admin', to='entreprise.entreprise', verbose_name='Entreprise partageur (admin)'),
        ),
        migrations.AddField(
            model_name='planificationml',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propositionprofil',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_recues', to='candidat.candidat', verbose_name='Candidat proposé'),
        ),
        migrations.AddField(
            model_name='propositionprofil',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_profils', to='entreprise.offreemploi', verbose_name='Offre'),
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, default='', max_length=255, verbose_name='Prénom')),
                ('dateNaissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('photoProfil', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Photo de profil')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse')),
                ('nomComplet', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom complet (legacy)')),
                ('emailProfessionnel', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email professionnel (legacy)')),
                ('dateEmbauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('roleMembre', models.CharField(choices=[('ADMIN', 'Administrateur'), ('RH', 'Responsable RH'), ('MANAGER', 'Manager'), ('LECTEUR', 'Lecteur')], default='RH', max_length=20, verbose_name='Rôle (legacy)')),
                ('droitsAcces', models.JSONField(default=dict, verbose_name="Droits d'accès")),
                ('estActif', models.BooleanField(default=True, verbose_name='Actif')),
                ('statutCompte', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('DESACTIVE', 'Désactivé')], default='ACTIF', max_length=20, verbose_name='Statut du compte')),
                ('emailVerifie', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('preferences', models.JSONField(default=dict, verbose_name='Préférences')),
                ('recevoirNotifsATS', models.BooleanField(default=True, help_text="Si désactivé, ne pas recevoir d'alerte quand un profil candidat correspond à une offre publiée.", verbose_name='Recevoir les notifications de profils ATS')),
                ('recevoirNotifsATSEmail', models.BooleanField(default=False, help_text='Si activé, recevoir aussi un email pour chaque alerte ATS.', verbose_name='Recevoir les notifications ATS par email')),
                ('derniereConnexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruteurs', to='entreprise.entreprise', verbose_name='Entreprise')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruteurs', to='referentiel.role', verbose_name='Rôle (référentiel)')),
                ('sexe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.sexe', verbose_name='Sexe')),
            ],
            options={
                'verbose_name': 'Recruteur',
                'verbose_name_plural': 'Recruteurs',
                'ordering': ['nomComplet'],
            },
            bases=('referentiel.utilisateur',),
        ),
        migrations.AddField(
            model_name='propositionprofil',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions_creees', to='entreprise.recruteur', verbose_name='Recruteur'),
        ),
        migrations.AddField(
            model_name='partageprofilexterne',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partages_profils', to='entreprise.recruteur', verbose_name='Recruteur partageur'),
        ),
        migrations.AddField(
            model_name='parametreentreprise',
            name='modifiePar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_modifies', to='entreprise.recruteur', verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='offreemploirecruteur',
            name='recruteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_createurs', to='entreprise.recruteur', verbose_name='Recruteur'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='creePar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_creees', to='entreprise.recruteur', verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='notificationrecruteur',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_envoyees', to='entreprise.recruteur', verbose_name='Expéditeur (suggestion)'),
        ),
        migrations.AddField(
            model_name='notificationrecruteur',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entreprise.recruteur', verbose_name='Recruteur'),
        ),
        migrations.AddField(
            model_name='modelemessage',
            name='creePar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_crees', to='entreprise.recruteur', verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='message',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to='entreprise.recruteur', verbose_name='Recruteur émetteur'),
        ),
        migrations.AddField(
            model_name='invitationpostuler',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_envoyees', to='entreprise.recruteur'),
        ),
        migrations.AddField(
            model_name='invitationentretien',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_invites', to='entreprise.recruteur'),
        ),
        migrations.AddField(
            model_name='conversationdirecte',
            name='recruteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='entreprise.recruteur'),
        ),
        migrations.CreateModel(
            name='TemoignageEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('poste', models.CharField(blank=True, default='', max_length=150, verbose_name='Poste / Entreprise')),
                ('texte', models.TextField(verbose_name='Témoignage')),
                ('note', models.PositiveSmallIntegerField(default=5, verbose_name='Note (1-5)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('publie', 'Publié'), ('rejete', 'Rejeté')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('entreprise', 'Entreprise')], default='admin', max_length=15, verbose_name='Source')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temoignages', to='entreprise.entreprise', verbose_name='Entreprise liée')),
            ],
            options={
                'verbose_name': 'Témoignage client',
                'verbose_name_plural': 'Témoignages clients',
                'ordering': ['ordre', '-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='TemoignageEnAttenteEntreprise',
            fields=[
            ],
            options={
                'verbose_name': 'Témoignage client en attente',
                'verbose_name_plural': 'Témoignages clients en attente',
                'ordering': ['-date_soumission'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('entreprise.temoignageentreprise',),
        ),
        migrations.CreateModel(
            name='TokenReinitialisationEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=5)),
                ('methode', models.CharField(choices=[('code', 'Code 5 chiffres'), ('lien', 'Lien')], default='lien', max_length=4)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('verifie', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_reinitialisation', to='entreprise.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Token réinitialisation MDP entreprise',
                'verbose_name_plural': 'Tokens réinitialisation MDP entreprises',
            },
        ),
        migrations.CreateModel(
            name='TokenVerificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=6, verbose_name='Code')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_expiration', models.DateTimeField(verbose_name='Expire le')),
                ('utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_verification_email', to='entreprise.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Token vérification email',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='propositionprofil',
            index=models.Index(fields=['offre', '-dateProposition'], name='entreprise__offre_i_20e19f_idx'),
        ),
        migrations.AddIndex(
            model_name='propositionprofil',
            index=models.Index(fields=['candidat', '-dateProposition'], name='entreprise__candida_b74c06_idx'),
        ),
        migrations.AddIndex(
            model_name='propositionprofil',
            index=models.Index(fields=['action'], name='entreprise__action_61ce9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propositionprofil',
            unique_together={('offre', 'candidat')},
        ),
        migrations.AddIndex(
            model_name='partageprofilexterne',
            index=models.Index(fields=['token'], name='entreprise__token_741cd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offreemploirecruteur',
            unique_together={('offre', 'recruteur')},
        ),
        migrations.AddIndex(
            model_name='notificationrecruteur',
            index=models.Index(fields=['recruteur', '-dateCreation'], name='entreprise__recrute_19c8de_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecruteur',
            index=models.Index(fields=['entreprise', '-dateCreation'], name='entreprise__entrepr_3f140f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecruteur',
            index=models.Index(fields=['recruteur', 'lue'], name='entreprise__recrute_6df111_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecruteur',
            index=models.Index(fields=['entreprise', 'lue'], name='entreprise__entrepr_7219ff_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecruteur',
            index=models.Index(fields=['type'], name='entreprise__type_50b21d_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationrecruteur',
            constraint=models.UniqueConstraint(condition=models.Q(('recruteur__isnull', False)), fields=('recruteur', 'offre', 'candidat', 'type'), name='uniq_notif_recruteur_offre_candidat_type'),
        ),
        migrations.AddConstraint(
            model_name='notificationrecruteur',
            constraint=models.UniqueConstraint(condition=models.Q(('entreprise__isnull', False)), fields=('entreprise', 'offre', 'candidat', 'type'), name='uniq_notif_entreprise_offre_candidat_type'),
        ),
        migrations.AddConstraint(
            model_name='notificationrecruteur',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entreprise__isnull', True), ('recruteur__isnull', False)), models.Q(('entreprise__isnull', False), ('recruteur__isnull', True)), _connector='OR'), name='notif_target_exclusif'),
        ),
        migrations.AddConstraint(
            model_name='modelemessage',
            constraint=models.UniqueConstraint(fields=('entreprise', 'sujet_modele'), name='unique_modele_par_entreprise_sujet'),
        ),
        migrations.AlterUniqueTogether(
            name='invitationpostuler',
            unique_together={('offre', 'candidat')},
        ),
        migrations.AlterUniqueTogether(
            name='invitationentretien',
            unique_together={('offre', 'candidat')},
        ),
        migrations.AlterUniqueTogether(
            name='conversationdirecte',
            unique_together={('recruteur', 'candidat')},
        ),
        migrations.AddConstraint(
            model_name='temoignageentreprise',
            constraint=models.UniqueConstraint(condition=models.Q(('entreprise__isnull', False)), fields=('entreprise',), name='unique_temoignage_par_entreprise'),
        ),
    ]
