# Generated by Django 6.0.5 on 2026-06-29 18:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import recrutement.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_initial'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeverification',
            name='document_identite',
            field=models.FileField(blank=True, null=True, storage=recrutement.storages.get_kyc_storage, upload_to='entreprise/verifications/identite/', verbose_name="Pièce d'identité dirigeant"),
        ),
        migrations.AlterField(
            model_name='demandeverification',
            name='document_rccm',
            field=models.FileField(blank=True, null=True, storage=recrutement.storages.get_kyc_storage, upload_to='entreprise/verifications/rccm/', verbose_name='Registre du commerce'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='logoEntreprise',
            field=models.ImageField(blank=True, null=True, storage=recrutement.storages.get_public_storage, upload_to='entreprise/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='photoProfil',
            field=models.ImageField(blank=True, null=True, storage=recrutement.storages.get_public_storage, upload_to='users/photos/', verbose_name='Photo de profil'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('raisonSocial', 'description', config='french'), name='idx_entreprise_fts'),
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('titre', 'missions', 'profilRecherche', config='french'), name='idx_offre_fts'),
        ),
    ]
