# Generated by Django 6.0.5 on 2026-07-09 12:15
# Passage de embedding (JSONField) à VectorField (pgvector) — édité à la main :
# jsonb -> vector n'a pas de cast implicite, donc ALTER COLUMN nécessite un
# USING explicite. Aucune offre n'avait d'embedding en cache au moment de
# cette migration (donnée recalculée à la demande, pas une source de vérité).

import pgvector.django.extensions
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_alter_demandeverification_document_identite_and_more'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        pgvector.django.extensions.VectorExtension(),
        migrations.RunSQL(
            sql='ALTER TABLE entreprise_offreemploi ALTER COLUMN embedding TYPE vector(384) USING NULL::vector(384);',
            reverse_sql='ALTER TABLE entreprise_offreemploi ALTER COLUMN embedding TYPE jsonb USING NULL::jsonb;',
            state_operations=[
                migrations.AlterField(
                    model_name='offreemploi',
                    name='embedding',
                    field=pgvector.django.vector.VectorField(blank=True, dimensions=384, editable=False, null=True, verbose_name='Embedding ATS'),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='offreemploi',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_offre_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
