# Generated by Django 6.0.5 on 2026-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_alter_offreemploi_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offreemploi',
            name='idx_offre_embedding_hnsw',
        ),
        migrations.RunSQL(
            sql=(
                'ALTER TABLE entreprise_offreemploi '
                'ALTER COLUMN embedding TYPE jsonb USING embedding::text::jsonb;'
            ),
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='offreemploi',
                    name='embedding',
                    field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Embedding ATS'),
                ),
            ],
        ),
    ]
