# Generated by Django 5.1.15 on 2026-07-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0006_fulltext_mysql'),
    ]

    operations = [
        # idx_entreprise_fts / idx_offre_fts (GinIndex, residu PostgreSQL)
        # n'ont jamais ete crees en base sous MySQL/MariaDB (W043 "does not
        # support indexes on expressions" au migrate) — SeparateDatabaseAndState
        # pour ne toucher que l'etat Django, RemoveIndex direct plante avec
        # "Can't DROP ... check that it exists" (erreur 1091).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='entreprise',
                    name='idx_entreprise_fts',
                ),
                migrations.RemoveIndex(
                    model_name='offreemploi',
                    name='idx_offre_fts',
                ),
            ],
            database_operations=[],
        ),
    ]
