# Generated by Django 6.0.5 on 2026-06-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Libellé')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie contact',
                'verbose_name_plural': 'Catégories contact',
                'ordering': ['ordre', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_affiche', models.EmailField(default='support@recrutepro.ci', max_length=254, verbose_name='Email affiché')),
                ('email_destination', models.EmailField(default='admin@recrutepro.ci', max_length=254, verbose_name='Email destinataire')),
                ('telephone', models.CharField(default='+225 07 00 00 00 00', max_length=30, verbose_name='Téléphone')),
                ('adresse', models.CharField(default='Cocody, Abidjan', max_length=200, verbose_name='Adresse')),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays')),
                ('horaires_semaine', models.CharField(default='Lundi – Vendredi : 8h – 18h', max_length=100, verbose_name='Horaires semaine')),
                ('horaires_samedi', models.CharField(blank=True, default='Samedi : 9h – 13h', max_length=100, verbose_name='Horaires samedi')),
                ('horaires_note', models.CharField(blank=True, default='Fermé les jours fériés', max_length=200, verbose_name='Note horaires')),
            ],
            options={
                'verbose_name': 'Configuration contact',
                'verbose_name_plural': 'Configuration contact',
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('categorie', models.CharField(max_length=80, verbose_name='Catégorie')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('repondu', models.BooleanField(default=False, verbose_name='Répondu')),
                ('repondu_le', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-cree_le'],
            },
        ),
    ]
