# Generated by Django 6.0.5 on 2026-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactconfig',
            name='email_affiche',
        ),
        migrations.RemoveField(
            model_name='contactconfig',
            name='email_destination',
        ),
        migrations.AddField(
            model_name='contactconfig',
            name='email',
            field=models.EmailField(default='support@recrutepro.ci', max_length=254, verbose_name='Email'),
        ),
    ]
