# Generated by Django 6.0.5 on 2026-06-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0002_simplify_contactconfig_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactconfig',
            name='faq_texte',
            field=models.CharField(blank=True, default='Consultez notre FAQ', max_length=100, verbose_name='Texte lien FAQ'),
        ),
    ]
