# Generated by Django 6.0.5 on 2026-06-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0005_pagestatique_sectionpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcategorie',
            name='categorie_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contenu.categorie'),
        ),
    ]
