# Generated by Django 6.0.5 on 2026-06-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0008_fonctionnaliteoffre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200, unique=True, verbose_name='Fonctionnalité')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Fonctionnalité',
                'verbose_name_plural': 'Fonctionnalités',
                'ordering': ['ordre', 'texte'],
            },
        ),
        migrations.RemoveField(
            model_name='offretarif',
            name='fonctionnalites',
        ),
        migrations.AddField(
            model_name='offretarif',
            name='fonctionnalites_choisies',
            field=models.ManyToManyField(blank=True, related_name='offres', to='contenu.fonctionnalite', verbose_name='Fonctionnalités'),
        ),
        migrations.DeleteModel(
            name='FonctionnaliteOffre',
        ),
    ]
