# Generated by Django 6.0.5 on 2026-07-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0009_fonctionnalite_remove_offretarif_fonctionnalites_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fonctionnalite',
            options={'ordering': ['ordre', 'texte'], 'verbose_name': 'Tarifaires fonctionnalité', 'verbose_name_plural': 'Tarifaires fonctionnalités'},
        ),
        migrations.AlterModelOptions(
            name='offretarif',
            options={'ordering': ['groupe', 'ordre'], 'verbose_name': 'Tarifaires offre', 'verbose_name_plural': 'Tarifaires offres'},
        ),
    ]
