# Generated by Django 6.0.5 on 2026-06-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneesExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name="Libellé d'expérience")),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Années d'expérience",
                'verbose_name_plural': "Années d'expérience",
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCertificat', models.CharField(max_length=200, verbose_name='Intitulé du certificat')),
                ('organisme', models.CharField(blank=True, max_length=150, verbose_name='Organisme certificateur')),
                ('domaine', models.CharField(blank=True, max_length=100, verbose_name='Domaine')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['domaine', 'nomCertificat'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé du contrat')),
            ],
            options={
                'verbose_name': 'Type de contrat',
                'verbose_name_plural': 'Types de contrat',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, unique=True, verbose_name='Libellé / code de la devise')),
                ('codeISO', models.CharField(blank=True, default='', max_length=10, verbose_name='Code ISO 4217')),
                ('symbole', models.CharField(blank=True, default='', max_length=5, verbose_name='Symbole')),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDiplome', models.CharField(max_length=200, verbose_name='Intitulé du diplôme')),
                ('domaine', models.CharField(blank=True, max_length=100, verbose_name='Domaine')),
            ],
            options={
                'verbose_name': 'Diplôme',
                'verbose_name_plural': 'Diplômes',
                'ordering': ['domaine', 'nomDiplome'],
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDomaine', models.CharField(max_length=150, unique=True, verbose_name='Nom du domaine')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
                'ordering': ['nomDomaine'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomInstitution', models.CharField(max_length=200, verbose_name="Nom de l'institution")),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['nomInstitution'],
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomLangue', models.CharField(max_length=100, verbose_name='Nom de la langue')),
                ('codeISO', models.CharField(blank=True, max_length=3, verbose_name='Code ISO')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['nomLangue'],
            },
        ),
        migrations.CreateModel(
            name='ModeEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé')),
                ('icone', models.CharField(blank=True, default='', max_length=10, verbose_name='Icône (emoji)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Mode d'entretien",
                'verbose_name_plural': "Modes d'entretien",
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ModeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé du mode de travail')),
            ],
            options={
                'verbose_name': 'Mode de travail',
                'verbose_name_plural': 'Modes de travail',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('langue', 'Langue'), ('competence', 'Compétence')], max_length=20, verbose_name='Catégorie de niveau')),
                ('nomNiveau', models.CharField(max_length=100, verbose_name='Code / nom du niveau')),
                ('libelle', models.CharField(blank=True, max_length=100, verbose_name='Libellé')),
                ('nbEtoiles', models.PositiveSmallIntegerField(default=0, verbose_name="Nombre d'étoiles (1-5)")),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['type', 'ordre', 'nomNiveau'],
            },
        ),
        migrations.CreateModel(
            name='NiveauEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomNiveau', models.CharField(max_length=100, verbose_name="Niveau d'étude")),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Niveau d'étude",
                'verbose_name_plural': "Niveaux d'étude",
                'ordering': ['ordre', 'nomNiveau'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPays', models.CharField(max_length=100, verbose_name='Nom du pays')),
                ('codeISO', models.CharField(max_length=3, unique=True, verbose_name='Code ISO')),
                ('estActif', models.BooleanField(default=True, verbose_name='Actif')),
                ('indicatifTel', models.CharField(blank=True, max_length=10, verbose_name='Indicatif téléphonique')),
                ('nationalite', models.CharField(blank=True, help_text='Gentilé du pays (ex : française, ivoirienne, sénégalaise)', max_length=100, verbose_name='Nationalité')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['nomPays'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPoste', models.CharField(max_length=200, verbose_name='Intitulé du poste')),
                ('domaine', models.CharField(blank=True, max_length=100, verbose_name='Domaine')),
            ],
            options={
                'verbose_name': 'Poste / Métier',
                'verbose_name_plural': 'Postes / Métiers',
                'ordering': ['domaine', 'nomPoste'],
            },
        ),
        migrations.CreateModel(
            name='ReseauSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=80, unique=True, verbose_name='Nom du réseau')),
                ('slug', models.SlugField(help_text="Slug officiel sur simpleicons.org (ex. 'linkedin', 'github', 'x').", max_length=80, unique=True, verbose_name='Identifiant simple-icons')),
                ('couleur', models.CharField(blank=True, default='', help_text="Code couleur hexadécimal sans #, ex. '0A66C2'. Vide = couleur par défaut.", max_length=7, verbose_name='Couleur de marque (hex)')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Réseau social',
                'verbose_name_plural': 'Réseaux sociaux',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé du rôle')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='SecteurActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSecteur', models.CharField(max_length=150, unique=True, verbose_name="Nom du secteur d'activité")),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Secteur d'activité",
                'verbose_name_plural': "Secteurs d'activité",
                'ordering': ['nomSecteur'],
            },
        ),
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(max_length=50, unique=True, verbose_name='Sexe')),
            ],
            options={
                'verbose_name': 'Sexe',
                'verbose_name_plural': 'Sexes',
                'ordering': ['sexe'],
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=80, verbose_name='Libellé')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('couleur', models.CharField(default='#94A3B8', max_length=7, verbose_name='Couleur (hex)')),
                ('icone', models.CharField(blank=True, default='', max_length=10, verbose_name='Icône (emoji)')),
                ('estFinal', models.BooleanField(default=False, help_text='Si vrai, plus aucune transition possible (embauche/refus/retrait).', verbose_name='Statut final')),
                ('estPositif', models.BooleanField(blank=True, help_text='True = succès, False = échec, None = en cours.', null=True, verbose_name='Issue positive ?')),
                ('estActif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Statut de candidature',
                'verbose_name_plural': 'Statuts de candidature',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='StatutCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé du statut')),
            ],
            options={
                'verbose_name': 'Statut de compte',
                'verbose_name_plural': 'Statuts de compte',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeCentreInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCentreInteret', models.CharField(max_length=150, verbose_name="Centre d'intérêt")),
            ],
            options={
                'verbose_name': "Centre d'intérêt",
                'verbose_name_plural': "Centres d'intérêt",
                'ordering': ['nomCentreInteret'],
            },
        ),
        migrations.CreateModel(
            name='TypeCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCompetence', models.CharField(max_length=150, verbose_name='Nom de la compétence')),
                ('domaine', models.CharField(blank=True, max_length=100, verbose_name='Domaine')),
            ],
            options={
                'verbose_name': 'Type de compétence',
                'verbose_name_plural': 'Types de compétences',
                'ordering': ['domaine', 'nomCompetence'],
            },
        ),
        migrations.CreateModel(
            name='TypeEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé')),
                ('icone', models.CharField(blank=True, default='', max_length=10, verbose_name='Icône (emoji)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Type d'entretien",
                'verbose_name_plural': "Types d'entretien",
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeMobilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé de la mobilité')),
            ],
            options={
                'verbose_name': 'Type de mobilité',
                'verbose_name_plural': 'Types de mobilité',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypePermis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPermis', models.CharField(max_length=20, verbose_name='Code permis')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Permis de conduire',
                'verbose_name_plural': 'Permis de conduire',
                'ordering': ['nomPermis'],
            },
        ),
        migrations.CreateModel(
            name='TypeRaisonSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRaisonSocial', models.CharField(max_length=200, verbose_name='Forme juridique')),
                ('secteur', models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité")),
            ],
            options={
                'verbose_name': 'Type de raison sociale',
                'verbose_name_plural': 'Types de raison sociale',
                'ordering': ['nomRaisonSocial'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('type_compte', models.CharField(blank=True, choices=[('CANDIDAT', 'Candidat'), ('RECRUTEUR', 'Recruteur')], default='', max_length=10, verbose_name='Type de compte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('referentiel.utilisateur',),
        ),
        migrations.CreateModel(
            name='RaisonSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEntreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('secteur', models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité")),
                ('typeRaisonSocial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises', to='referentiel.typeraisonsociale', verbose_name='Forme juridique')),
            ],
            options={
                'verbose_name': 'Raison sociale',
                'verbose_name_plural': 'Raisons sociales',
                'ordering': ['nomEntreprise'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomVille', models.CharField(max_length=100, verbose_name='Nom de la ville')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('estActif', models.BooleanField(default=True, verbose_name='Actif')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='referentiel.pays', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nomVille'],
            },
        ),
    ]
