# Generated by Django 6.0.5 on 2026-06-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=80, verbose_name='Titre')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Groupe footer',
                'verbose_name_plural': 'Groupes footer',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ElementFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIEN', 'Lien'), ('BOUTON', 'Bouton')], default='LIEN', max_length=6, verbose_name='Type')),
                ('label', models.CharField(max_length=120, verbose_name='Label')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('nouvel_onglet', models.BooleanField(default=False, verbose_name='Nouvel onglet')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='pages.groupefooter')),
            ],
            options={
                'verbose_name': 'Élément footer',
                'verbose_name_plural': 'Éléments footer',
                'ordering': ['ordre'],
            },
        ),
    ]
