# Generated by Django 6.0.5 on 2026-06-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupefooter',
            name='cible',
            field=models.CharField(choices=[('CANDIDAT', 'Candidat seulement'), ('ENTREPRISE', 'Entreprise seulement'), ('LES_DEUX', 'Les deux')], default='LES_DEUX', max_length=10, verbose_name='Affiché dans'),
        ),
    ]
