# Generated by Django 6.0.5 on 2026-06-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_replace_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementfooter',
            name='visibilite',
            field=models.CharField(choices=[('TOUJOURS', 'Toujours'), ('CANDIDAT_CONNECTE', 'Candidat connecté'), ('CANDIDAT_NON_CONNECTE', 'Candidat non connecté'), ('ENTREPRISE', 'Entreprise connectée'), ('RECRUTEUR', 'Recruteur connecté'), ('ENTREPRISE_OU_RECRUTEUR', 'Entreprise ou Recruteur')], default='TOUJOURS', max_length=25, verbose_name='Visibilité'),
        ),
    ]
