# Generated by Django 6.0.5 on 2026-06-28 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_footergroupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeelement',
            name='contenu',
            field=models.ForeignKey(blank=True, help_text='Pour un menu déroulant : groupe dont les éléments seront affichés comme sous-liens.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_contenu', to='pages.groupe', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='element',
            name='url',
            field=models.CharField(blank=True, default='', help_text='<strong>Candidat</strong> → commence par <code>/candidat/</code><br><strong>Entreprise</strong> → commence par <code>/entreprise/</code><br><strong>Les deux</strong> → ex: <em>/faq/</em> · <em>/contact/</em><br><strong>Lien externe</strong> → <code>https://exemple.com</code><br><strong>Menu déroulant</strong> → laisser vide.', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='element',
            name='visibilite',
            field=models.CharField(choices=[('TOUJOURS', 'Toujours'), ('CANDIDAT_CONNECTE', 'Candidat connecté'), ('CANDIDAT_NON_CONNECTE', 'Candidat non connecté'), ('ENTREPRISE', 'Entreprise connectée'), ('RECRUTEUR', 'Recruteur connecté'), ('RECRUTEUR_ADMIN', 'Recruteur admin'), ('ENTREPRISE_OU_RECRUTEUR', 'Entreprise ou Recruteur')], default='TOUJOURS', max_length=25, verbose_name='Visibilité'),
        ),
        migrations.AlterField(
            model_name='footergroupe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='elements',
            field=models.ManyToManyField(blank=True, related_name='groupes', through='pages.GroupeElement', through_fields=('groupe', 'element'), to='pages.element', verbose_name='Éléments'),
        ),
        migrations.AlterField(
            model_name='groupeelement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupeelement',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un lien de premier niveau. Sélectionner un Menu déroulant pour en faire un sous-élément.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='pages.groupeelement', verbose_name='Élément parent'),
        ),
    ]
