# Generated by Django 6.0.5 on 2026-06-28 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_contenu_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDeroulant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120, verbose_name='Titre')),
                ('visibilite', models.CharField(choices=[('TOUJOURS', 'Toujours'), ('CANDIDAT_CONNECTE', 'Candidat connecté'), ('CANDIDAT_NON_CONNECTE', 'Candidat non connecté'), ('ENTREPRISE', 'Entreprise connectée'), ('RECRUTEUR', 'Recruteur connecté'), ('RECRUTEUR_ADMIN', 'Recruteur admin'), ('ENTREPRISE_OU_RECRUTEUR', 'Entreprise ou Recruteur')], default='TOUJOURS', max_length=25, verbose_name='Visibilité')),
                ('icone', models.CharField(blank=True, default='', max_length=10, verbose_name='Icône')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Menu déroulant',
                'verbose_name_plural': 'Menus déroulants',
                'ordering': ['titre'],
            },
        ),
        migrations.AlterModelOptions(
            name='menuderoulantproxy',
            options={'verbose_name': 'Menu déroulant (ancien)', 'verbose_name_plural': 'Menus déroulants (anciens)'},
        ),
        migrations.RemoveField(
            model_name='groupeelement',
            name='contenu',
        ),
        migrations.AlterField(
            model_name='groupeelement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='pages.groupeelement', verbose_name='Élément parent'),
        ),
        migrations.AddField(
            model_name='groupeelement',
            name='menu_deroulant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navbar_items', to='pages.menuderoulant', verbose_name='Menu déroulant'),
        ),
        migrations.CreateModel(
            name='MenuDeroulantElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.element')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_elements', to='pages.menuderoulant')),
            ],
            options={
                'verbose_name': 'Élément du menu',
                'verbose_name_plural': 'Éléments du menu',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='menuderoulant',
            name='elements',
            field=models.ManyToManyField(blank=True, related_name='menus_deroulants', through='pages.MenuDeroulantElement', to='pages.element', verbose_name='Éléments (liens directs)'),
        ),
        migrations.CreateModel(
            name='MenuDeroulantGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.groupe')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_groupes', to='pages.menuderoulant')),
            ],
            options={
                'verbose_name': 'Groupe du menu',
                'verbose_name_plural': 'Groupes du menu',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='menuderoulant',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='menus_deroulants', through='pages.MenuDeroulantGroupe', to='pages.groupe', verbose_name='Groupes (liens du groupe)'),
        ),
    ]
