# Generated by Django 6.0.5 on 2026-06-20 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('token_desabonnement', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de désabonnement')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('offres_semaine', models.BooleanField(default=False, verbose_name='Offres de la semaine')),
                ('conseils', models.BooleanField(default=False, verbose_name='Conseils & astuces')),
                ('actualites', models.BooleanField(default=False, verbose_name='Actualités de la plateforme')),
                ('offres_perso', models.BooleanField(default=False, verbose_name='Offres correspondant à mon profil')),
                ('profil_consulte', models.BooleanField(default=False, verbose_name='Quand mon profil est consulté')),
                ('resume_candidatures', models.BooleanField(default=False, verbose_name='Résumé de mes candidatures')),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='ActualiteNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, help_text='Optionnel. Recommandé : 600×300 px.', null=True, upload_to='newsletter/actualites/', verbose_name='Image')),
                ('legende_image', models.CharField(blank=True, default='', max_length=200, verbose_name="Légende de l'image")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIE', 'Planifié'), ('ENVOYE', 'Envoyé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_envoi_prevu', models.DateTimeField(blank=True, help_text="Laissez vide pour un envoi immédiat depuis l'admin.", null=True, verbose_name="Date d'envoi planifiée")),
                ('date_envoi_reel', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi réelle")),
                ('nb_destinataires', models.IntegerField(default=0, verbose_name='Destinataires')),
            ],
            options={
                'verbose_name': 'Actualité newsletter',
                'verbose_name_plural': 'Actualités newsletter',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Benevolat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, default='', max_length=255, verbose_name='Titre / rôle')),
                ('organisation', models.CharField(blank=True, default='', max_length=255, verbose_name='Organisation')),
                ('dateDebut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('dateFin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('enCours', models.BooleanField(default=False, verbose_name='En cours')),
                ('estVisiblePortfolio', models.BooleanField(default=True, verbose_name='Visible sur le portfolio')),
            ],
            options={
                'verbose_name': 'Bénévolat',
                'verbose_name_plural': 'Bénévolats',
                'ordering': ['-dateDebut', 'id'],
            },
        ),
    ]
