# Generated by Django 6.0.5 on 2026-06-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidat', '0002_initial'),
        ('entreprise', '0002_initial'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='createPar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_planifies', to='entreprise.recruteur', verbose_name='Planifié par'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='modeRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entretiens', to='referentiel.modeentretien', verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='typeEntretienRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entretiens', to='referentiel.typeentretien', verbose_name="Type d'entretien"),
        ),
        migrations.AddField(
            model_name='experienceprofessionnelle',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencesProfessionnelles', to='candidat.candidat', verbose_name='Candidat'),
        ),
        migrations.AddField(
            model_name='experienceprofessionnelle',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.raisonsociale', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='experienceprofessionnelle',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.pays', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='cvcontenu',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='contenusCv', to='candidat.experienceprofessionnelle', verbose_name='Expériences'),
        ),
        migrations.AddField(
            model_name='formation',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='candidat.candidat', verbose_name='Candidat'),
        ),
        migrations.AddField(
            model_name='formation',
            name='diplomeRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.diplome', verbose_name='Diplôme (référentiel)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.domaine', verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='formation',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.institution', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='formation',
            name='niveauEtude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.niveauetude', verbose_name="Niveau d'étude"),
        ),
        migrations.AddField(
            model_name='formation',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.pays', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='cvcontenu',
            name='formations',
            field=models.ManyToManyField(blank=True, related_name='contenusCv', to='candidat.formation', verbose_name='Formations'),
        ),
        migrations.AddField(
            model_name='historiquestatut',
            name='ancienStatut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiel.statut', verbose_name='Ancien statut'),
        ),
        migrations.AddField(
            model_name='historiquestatut',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='candidat.candidature', verbose_name='Candidature'),
        ),
        migrations.AddField(
            model_name='historiquestatut',
            name='nouveauStatut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='referentiel.statut', verbose_name='Nouveau statut'),
        ),
        migrations.AddField(
            model_name='cvcontenu',
            name='informationPersonnelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='candidat.informationpersonnelle', verbose_name='Informations personnelles'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='informationPersonnelle',
            field=models.OneToOneField(blank=True, help_text='Champ transitoire — sera supprimé après migration des données.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to='candidat.informationpersonnelle', verbose_name='Informations personnelles (legacy)'),
        ),
        migrations.AddField(
            model_name='lettrecontenu',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.raisonsociale', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='lettrecontenu',
            name='informationPersonnelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='candidat.informationpersonnelle', verbose_name='Informations personnelles'),
        ),
        migrations.AddField(
            model_name='lettrecontenu',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.pays', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='lettrecontenu',
            name='posteDestinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.poste', verbose_name='Poste du destinataire'),
        ),
        migrations.AddField(
            model_name='lettrecontenu',
            name='villeEntreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.ville', verbose_name="Ville de l'entreprise"),
        ),
        migrations.AddField(
            model_name='lettremotivation',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettres', to='candidat.candidat', verbose_name='Candidat'),
        ),
        migrations.AddField(
            model_name='lettremotivation',
            name='contenu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettre', to='candidat.lettrecontenu', verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='lettreSauvegardee',
            field=models.ForeignKey(blank=True, help_text="Si le candidat réutilise une lettre qu'il a créée sur le site.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='candidat.lettremotivation', verbose_name='Lettre RecrutePro (réutilisée)'),
        ),
        migrations.AddField(
            model_name='liencandidat',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liensSociaux', to='candidat.candidat', verbose_name='Candidat'),
        ),
        migrations.AddField(
            model_name='liencandidat',
            name='reseau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liens', to='referentiel.reseausocial', verbose_name='Réseau'),
        ),
        migrations.AddField(
            model_name='missionclient',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.raisonsociale', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='missionclient',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missionsClient', to='candidat.experienceprofessionnelle', verbose_name='Expérience'),
        ),
        migrations.AddField(
            model_name='missionclient',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.pays', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='cv',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvs', to='candidat.modelecv', verbose_name='Modèle de CV'),
        ),
        migrations.AddField(
            model_name='lettremotivation',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettres', to='candidat.modelelettre', verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='notificationcandidat',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='candidat.candidat', verbose_name='Candidat'),
        ),
        migrations.AddField(
            model_name='notificationcandidat',
            name='messageRecruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_candidat', to='entreprise.message', verbose_name='Message du recruteur lié'),
        ),
        migrations.AddField(
            model_name='notificationcandidat',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entreprise.offreemploi', verbose_name='Offre concernée'),
        ),
        migrations.AddField(
            model_name='offrefavori',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_favorites', to='candidat.candidat'),
        ),
        migrations.AddField(
            model_name='offrefavori',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_en_favori', to='entreprise.offreemploi'),
        ),
        migrations.AddField(
            model_name='photocv',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='candidat.cv', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='photolettre',
            name='lettre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='candidat.lettremotivation', verbose_name='Lettre'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='portfolioModele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='candidat.portfolio', verbose_name='Modèle de portfolio choisi'),
        ),
        migrations.AddField(
            model_name='posteoccupe',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='candidat.experienceprofessionnelle', verbose_name='Expérience'),
        ),
        migrations.AddField(
            model_name='posteoccupe',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.poste', verbose_name='Poste (référentiel)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='candidat.candidat', verbose_name='Candidat'),
        ),
        migrations.AddField(
            model_name='projet',
            name='experienceProfessionnelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='candidat.experienceprofessionnelle', verbose_name='Expérience associée'),
        ),
        migrations.AddField(
            model_name='cvcontenu',
            name='projets',
            field=models.ManyToManyField(blank=True, related_name='contenusCv', to='candidat.projet', verbose_name='Projets'),
        ),
        migrations.AddField(
            model_name='temoignage',
            name='candidat',
            field=models.ForeignKey(blank=True, help_text='Lié automatiquement pour les soumissions candidat. Vide pour les témoignages admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temoignages', to='candidat.candidat', verbose_name='Candidat'),
        ),
        migrations.CreateModel(
            name='TemoignageEnAttente',
            fields=[
            ],
            options={
                'verbose_name': 'Témoignage en attente',
                'verbose_name_plural': 'Témoignages en attente',
                'ordering': ['-date_soumission'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('candidat.temoignage',),
        ),
        migrations.AddField(
            model_name='tokenconfirmationinscription',
            name='candidat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_confirmation', to='candidat.candidat', verbose_name='Candidat'),
        ),
        migrations.AddField(
            model_name='tokenreinitialisationmdp',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_reinitialisation', to='candidat.candidat'),
        ),
        migrations.AlterUniqueTogether(
            name='visiteip',
            unique_together={('date', 'adresse_ip')},
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('candidat', 'offre'), name='unique_candidature_par_offre'),
        ),
        migrations.AddConstraint(
            model_name='liencandidat',
            constraint=models.UniqueConstraint(fields=('candidat', 'reseau'), name='unique_lien_candidat_reseau'),
        ),
        migrations.AddConstraint(
            model_name='cv',
            constraint=models.UniqueConstraint(condition=models.Q(('nomCv', ''), _negated=True), fields=('candidat', 'nomCv'), name='unique_nomcv_par_candidat'),
        ),
        migrations.AddIndex(
            model_name='notificationcandidat',
            index=models.Index(fields=['candidat', '-dateCreation'], name='candidat_no_candida_16b495_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcandidat',
            index=models.Index(fields=['candidat', 'lue'], name='candidat_no_candida_851d6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationcandidat',
            constraint=models.UniqueConstraint(condition=models.Q(('offre__isnull', False)), fields=('candidat', 'offre', 'type'), name='unique_notification_par_offre'),
        ),
        migrations.AlterUniqueTogether(
            name='offrefavori',
            unique_together={('candidat', 'offre')},
        ),
        migrations.AlterUniqueTogether(
            name='photocv',
            unique_together={('cv', 'numeroPage')},
        ),
        migrations.AlterUniqueTogether(
            name='photolettre',
            unique_together={('lettre', 'numeroPage')},
        ),
        migrations.AddConstraint(
            model_name='temoignage',
            constraint=models.UniqueConstraint(condition=models.Q(('candidat__isnull', False)), fields=('candidat',), name='unique_temoignage_par_candidat'),
        ),
    ]
