# Generated by Django 6.0.5 on 2026-06-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='lienGithub',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='lienLinkedin',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='lienSiteWeb',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='lienTwitter',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='lienYoutube',
        ),
    ]
