# Generated by Django 6.0.5 on 2026-06-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0004_supprimer_liens_sociaux_legacy'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motsCles', models.CharField(blank=True, help_text='Intitulé de poste ou mots-clés séparés par des virgules.', max_length=200, verbose_name='Mots-clés')),
                ('typeContrat', models.CharField(blank=True, help_text='Laisser vide pour tous les types.', max_length=20, verbose_name='Type de contrat')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('salaireMin', models.IntegerField(blank=True, null=True, verbose_name='Salaire min (FCFA)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('creeLe', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertesEmploi', to='candidat.candidat', verbose_name='Candidat')),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='referentiel.secteuractivite', verbose_name="Secteur d'activité")),
            ],
            options={
                'verbose_name': 'Alerte emploi',
                'verbose_name_plural': 'Alertes emploi',
                'ordering': ['-creeLe'],
            },
        ),
        migrations.AddField(
            model_name='candidat',
            name='recommandationsActives',
            field=models.BooleanField(default=True, help_text="Si activé, notre IA analyse votre profil et vous suggère automatiquement les offres les plus pertinentes.", verbose_name='Recommandations automatiques actives'),
        ),
    ]
