# Generated by Django 6.0.5 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0005_alertes_emploi_et_recommandations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerteemploi',
            name='motsCles',
            field=models.CharField(
                blank=True,
                help_text='Intitulés de postes séparés par des virgules (ex : Comptable, Ingénieur).',
                max_length=500,
                verbose_name='Mots-clés',
            ),
        ),
        migrations.AlterField(
            model_name='alerteemploi',
            name='typeContrat',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Liste des types souhaités (ex : ["CDI","CDD"]). Vide = tous.',
                verbose_name='Types de contrat',
            ),
        ),
        migrations.AlterField(
            model_name='alerteemploi',
            name='ville',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Liste des villes souhaitées (ex : ["Abidjan","Yamoussoukro"]). Vide = toutes.',
                verbose_name='Villes',
            ),
        ),
    ]
