# Generated by Django 6.0.5 on 2026-06-29 18:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import recrutement.storages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0007_candidat_alertes_actives'),
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualitenewsletter',
            name='image',
            field=models.ImageField(blank=True, help_text='Optionnel. Recommandé : 600×300 px.', null=True, storage=recrutement.storages.get_public_storage, upload_to='newsletter/actualites/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='photoProfil',
            field=models.ImageField(blank=True, null=True, storage=recrutement.storages.get_public_storage, upload_to='users/photos/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photoProfil',
            field=models.ImageField(blank=True, null=True, storage=recrutement.storages.get_public_storage, upload_to='candidat/photos/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='logosite',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='PNG transparent ou SVG recommandé. Hauteur idéale : 40–60 px.', null=True, storage=recrutement.storages.get_public_storage, upload_to='site/logo/', verbose_name='Image du logo'),
        ),
        migrations.AlterField(
            model_name='modelecv',
            name='apercu',
            field=models.ImageField(blank=True, help_text="Capture d'écran du rendu du modèle (format recommandé : 794×1123 px)", null=True, storage=recrutement.storages.get_public_storage, upload_to='modeles_cv/apercu/', verbose_name="Image d'aperçu"),
        ),
        migrations.AlterField(
            model_name='modelelettre',
            name='apercu',
            field=models.ImageField(blank=True, help_text='Capture A4 du rendu (794×1123 px recommandé)', null=True, storage=recrutement.storages.get_public_storage, upload_to='modeles_lettre/apercu/', verbose_name="Image d'aperçu"),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='apercu',
            field=models.ImageField(blank=True, help_text='Capture du rendu (recommandé : 1280×720 px).', null=True, storage=recrutement.storages.get_public_storage, upload_to='portfolios/apercu/', verbose_name="Image d'aperçu"),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('nom', 'prenom', 'titreProfessionnel', 'biographie', config='french'), name='idx_candidat_fts'),
        ),
    ]
