# Generated by Django 6.0.5 on 2026-07-09 12:15
# Passage de embedding (JSONField) à VectorField (pgvector) — édité à la main :
# jsonb -> vector n'a pas de cast implicite, donc ALTER COLUMN nécessite un
# USING explicite. Un seul candidat sur 117 avait un embedding en cache (une
# donnée recalculée à la demande, pas une source de vérité) : on le remet à
# NULL au passage plutôt que de tenter une conversion jsonb -> vector fragile.

import pgvector.django.extensions
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0008_alter_actualitenewsletter_image_and_more'),
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgvector.django.extensions.VectorExtension(),
        migrations.RunSQL(
            sql='ALTER TABLE candidat_candidat ALTER COLUMN embedding TYPE vector(384) USING NULL::vector(384);',
            reverse_sql='ALTER TABLE candidat_candidat ALTER COLUMN embedding TYPE jsonb USING NULL::jsonb;',
            state_operations=[
                migrations.AlterField(
                    model_name='candidat',
                    name='embedding',
                    field=pgvector.django.vector.VectorField(blank=True, dimensions=384, editable=False, null=True, verbose_name='Embedding ATS'),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_candidat_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
