# Generated by Django 6.0.5 on 2026-07-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0009_alter_candidat_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelelettre',
            name='famille',
            field=models.CharField(choices=[('classique', 'Classique — bloc unique'), ('sidebar', 'Bandeau latéral persistant'), ('accroche', 'Accroche mise en avant'), ('carte', 'Carte encadrée')], default='classique', help_text='Structure HTML utilisée par lettre_render.html (voir bloc {% if modele.famille == ... %}).', max_length=20, verbose_name='Famille de mise en page'),
        ),
    ]
