# Generated by Django 6.0.5 on 2026-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0010_modelelettre_famille'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidat',
            name='idx_candidat_embedding_hnsw',
        ),
        migrations.RunSQL(
            sql=(
                'ALTER TABLE candidat_candidat '
                'ALTER COLUMN embedding TYPE jsonb USING embedding::text::jsonb;'
            ),
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='candidat',
                    name='embedding',
                    field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Embedding ATS'),
                ),
            ],
        ),
    ]
