# Generated by Django 5.1.15 on 2026-07-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0012_fulltext_mysql'),
    ]

    operations = [
        # idx_candidat_fts (GinIndex, residu PostgreSQL) n'a jamais ete cree
        # en base sous MySQL/MariaDB (W043 "does not support indexes on
        # expressions" au migrate) — SeparateDatabaseAndState pour ne
        # toucher que l'etat Django, RemoveIndex direct plante avec
        # "Can't DROP ... check that it exists" (erreur 1091).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='candidat',
                    name='idx_candidat_fts',
                ),
            ],
            database_operations=[],
        ),
    ]
